export const texts = [
  {
    id: 1,
    author: "rose",
    title: "Los abrazos",
    genre: "writing",
    date: "11 may, 2020",
    picUrl:
      "https://pm1.narvii.com/7642/237e0075d6b3a92bb43fff15b32cf19bd1d6fcd2r1-731-1024v2_hq.jpg",
    category: "amor",
    likes: 523,
    views: 1235,
    overview:
      "El amor es una enfermedad de las más jodidas y contagiosas. A los enfermos cualquiera nos reconoce. Hondas ojeras delatan que jamás dormimos, despabilados noche tras noche por los abrazos,",
    tags: [
      { id: 1, title: "amor" },
      { id: 2, title: "desamor" },
      { id: 3, title: "fe" },
      { id: 4, title: "motivacional" },
      { id: 5, title: "poetico" },
      { id: 6, title: "amor" },
      { id: 7, title: "desamor" },
      { id: 8, title: "fe" },
      { id: 9, title: "motivacional" },
      { id: 10, title: "poetico" },
    ],
  },
  {
    id: 2,
    author: "juen_lo",
    title: "El mundo",
    genre: "writing",
    picUrl:
      "https://2.bp.blogspot.com/-R61AehyuPRI/TwgTpQqMX0I/AAAAAAAA5wM/NdQz6dtPZr8/w1200-h630-p-k-no-nu/El+ajenjo1.jpg",
    date: "11 may, 2020",
    category: "melancolía",
    likes: 710,
    views: 2356,
    overview:
      "Un hombre del pueblo de Negua, en la costa de Colombia, pudo subir al alto cielo. A la vuelta, contó. Dijo que había contemplado, desde allá arriba, la vida humana. Y dijo que somos un mar de fueguitos",
    tags: [
      { id: 1, title: "amor" },
      { id: 2, title: "desamor" },
      { id: 3, title: "fe" },
      { id: 4, title: "motivacional" },
      { id: 5, title: "poetico" },
      { id: 6, title: "amor" },
      { id: 7, title: "desamor" },
      { id: 8, title: "fe" },
    ],
  },
  {
    id: 3,
    author: "justmi",
    title: "Ocaso",
    genre: "writing",
    picUrl:
      "https://c.wallhere.com/photos/12/ea/1534x863_px_artwork_Leonid_Afremov_painting_Sailboats_sea-514537.jpg!d",
    date: "11 may, 2020",
    category: "amor",
    likes: 1420,
    views: 3154,
    overview:
      "¿Cómo explican los sentimientos agradables? Afirmando que están determinados por la confianza de Dios, por la conciencia de haber hecho una buena acción (lo que llaman buena conciencia es un estado",
    tags: [
      { id: 1, title: "amor" },
      { id: 2, title: "desamor" },
      { id: 3, title: "fe" },
      { id: 4, title: "motivacional" },
      { id: 5, title: "poetico" },
      { id: 6, title: "motivacional" },
      { id: 7, title: "poetico" },
    ],
  },
  {
    id: 4,
    author: "dipme",
    title: "Charles",
    genre: "writing",
    picUrl: "https://huellas01.web.app/css/img/writing-4.jpg",
    date: "11 may, 2020",
    category: "pasión",
    likes: 1230,
    views: 3456,
    overview:
      "Ahora, cuando cae la tarde tan despacio, me sorprendo arrimado al espejo nocturno, al silencio tan denso de miradas: parezco una lejana voz que apenas se dice, que despide amarilla al día que se fuga. Un día más se va.",
    tags: [
      { id: 1, title: "amor" },
      { id: 2, title: "desamor" },
      { id: 3, title: "fe" },
      { id: 4, title: "motivacional" },
      { id: 5, title: "poetico" },
      { id: 6, title: "desamor" },
      { id: 7, title: "desamor" },
      { id: 8, title: "fe" },
      { id: 9, title: "motivacional" },
      { id: 10, title: "motivacional" },
      { id: 11, title: "poetico" },
      { id: 12, title: "fe" },
    ],
  },
  {
    id: 5,
    author: "redstone",
    title: "Vos",
    genre: "poem",
    picUrl: "https://huellas01.web.app/css/img/poem-1.jpg",
    date: "11 may, 2020",
    category: "desamor",
    likes: 3702,
    views: 6540,
    overview:
      "Tengo la sensación de que algo me falta, no sé bien si seas vos o más alcohol, así que por si no volves, iré a conseguir cerveza, y si vienes, por favor trae cerveza. Lo sé, yo también odio ese vicio. Por eso te pido que",
    tags: [
      { id: 1, title: "amor" },
      { id: 2, title: "desamor" },
      { id: 3, title: "fe" },
      { id: 4, title: "motivacional" },
      { id: 5, title: "poetico" },
      { id: 6, title: "desamor" },
      { id: 7, title: "fe" },
      { id: 8, title: "motivacional" },
      { id: 9, title: "motivacional" },
      { id: 10, title: "poetico" },
      { id: 11, title: "fe" },
    ],
  },
  {
    id: 6,
    author: "famuel",
    title: "Fe",
    genre: "writing",
    picUrl: "https://huellas01.web.app/css/img/writing-6.jpg",
    date: "11 may, 2020",
    category: "religión",
    likes: 621,
    views: 1202,
    overview:
      "Sin fe, no tenemos esperanza, y sin esperanza no tenemos propiamente vida. No teniendo una idea del futuro, tampoco tenemos una idea de hoy, porque el hoy, para el hombre de acción, no es sino un prólogo del futuro",
    tags: [
      { id: 1, title: "amor" },
      { id: 2, title: "desamor" },
      { id: 3, title: "fe" },
      { id: 4, title: "motivacional" },
      { id: 5, title: "poetico" },
      { id: 6, title: "desamor" },
      { id: 7, title: "fe" },
      { id: 8, title: "motivacional" },
      { id: 9, title: "motivacional" },
      { id: 10, title: "poetico" },
      { id: 11, title: "fe" },
      { id: 12, title: "motivacional" },
      { id: 13, title: "poetico" },
    ],
  },
  {
    id: 7,
    author: "JenniferDel",
    title: "Charles",
    genre: "writing",
    picUrl: "https://huellas01.web.app/css/img/writing-4.jpg",
    date: "11 may, 2020",
    category: "amor",
    likes: 5520,
    views: 9853,
    overview:
      "Ahora, cuando cae la tarde tan despacio, me sorprendo arrimado al espejo nocturno, al silencio tan denso de miradas: parezco una lejana voz que apenas se dice, que despide amarilla al día que se fuga. Un día más se va.",
    tags: [
      { id: 1, title: "amor" },
      { id: 2, title: "desamor" },
      { id: 3, title: "fe" },
      { id: 4, title: "motivacional" },
      { id: 5, title: "poetico" },
      { id: 6, title: "desamor" },
      { id: 7, title: "fe" },
      { id: 8, title: "motivacional" },
      { id: 9, title: "poetico" },
      { id: 10, title: "fe" },
      { id: 11, title: "motivacional" },
      { id: 12, title: "poetico" },
    ],
  },
  {
    id: 8,
    author: "TedReste",
    title: "Vos",
    genre: "poem",
    picUrl: "https://huellas01.web.app/css/img/poem-1.jpg",
    date: "11 may, 2020",
    category: "amor",
    likes: 1230,
    views: 2356,
    overview:
      "Tengo la sensación de que algo me falta, no sé bien si seas vos o más alcohol, así que por si no volves, iré a conseguir cerveza, y si vienes, por favor trae cerveza. Lo sé, yo también odio ese vicio. Por eso te pido que",
    tags: [
      { id: 1, title: "amor" },
      { id: 2, title: "desamor" },
      { id: 3, title: "fe" },
      { id: 4, title: "motivacional" },
      { id: 5, title: "poetico" },
      { id: 6, title: "fe" },
      { id: 7, title: "motivacional" },
      { id: 8, title: "poetico" },
    ],
  },
  {
    id: 9,
    author: "JoeGoldberg",
    title: "Fe",
    genre: "writing",
    picUrl: "https://huellas01.web.app/css/img/writing-6.jpg",
    date: "11 may, 2020",
    category: "amor",
    likes: 722,
    views: 1463,
    overview:
      "Sin fe, no tenemos esperanza, y sin esperanza no tenemos propiamente vida. No teniendo una idea del futuro, tampoco tenemos una idea de hoy, porque el hoy, para el hombre de acción, no es sino un prólogo del futuro",
    tags: [
      { id: 1, title: "amor" },
      { id: 2, title: "desamor" },
      { id: 3, title: "fe" },
      { id: 4, title: "motivacional" },
      { id: 5, title: "poetico" },
      { id: 6, title: "desamor" },
      { id: 7, title: "fe" },
      { id: 8, title: "motivacional" },
      { id: 9, title: "poetico" },
    ],
  },
  {
    id: 10,
    author: "eSmI",
    title: "Charles",
    genre: "writing",
    picUrl: "https://huellas01.web.app/css/img/writing-4.jpg",
    date: "11 may, 2020",
    category: "amor",
    likes: 5405,
    views: 9856,
    overview:
      "Ahora, cuando cae la tarde tan despacio, me sorprendo arrimado al espejo nocturno, al silencio tan denso de miradas: parezco una lejana voz que apenas se dice, que despide amarilla al día que se fuga. Un día más se va.",
    tags: [
      { id: 1, title: "amor" },
      { id: 2, title: "desamor" },
      { id: 3, title: "fe" },
      { id: 4, title: "motivacional" },
      { id: 5, title: "poetico" },
    ],
  },
  {
    id: 11,
    author: "esTers",
    title: "Vos",
    genre: "poem",
    picUrl: "https://huellas01.web.app/css/img/poem-1.jpg",
    date: "11 may, 2020",
    category: "amor",
    likes: 3100,
    views: 5632,
    overview:
      "Tengo la sensación de que algo me falta, no sé bien si seas vos o más alcohol, así que por si no volves, iré a conseguir cerveza, y si vienes, por favor trae cerveza. Lo sé, yo también odio ese vicio. Por eso te pido que",
    tags: [
      { id: 1, title: "amor" },
      { id: 2, title: "desamor" },
      { id: 3, title: "fe" },
      { id: 4, title: "motivacional" },
      { id: 5, title: "poetico" },
      { id: 6, title: "motivacional" },
      { id: 7, title: "poetico" },
    ],
  },
  {
    id: 12,
    author: "rose",
    title: "Fe",
    genre: "writing",
    picUrl: "https://huellas01.web.app/css/img/writing-6.jpg",
    date: "11 may, 2020",
    category: "amor",
    likes: 5350,
    views: 8789,
    overview:
      "Sin fe, no tenemos esperanza, y sin esperanza no tenemos propiamente vida. No teniendo una idea del futuro, tampoco tenemos una idea de hoy, porque el hoy, para el hombre de acción, no es sino un prólogo del futuro",
    tags: [
      { id: 1, title: "amor" },
      { id: 2, title: "desamor" },
      { id: 3, title: "fe" },
    ],
  },
];
