import stairs from "../../../../assets/images/stairs.jpg";
import woods from "../../../../assets/images/woods.jpg";
import train from "../../../../assets/images/train.jpg";
import people from "../../../../assets/images/people.jpg";
import rose from "../../../../assets/images/rose.jpg";
import girl from "../../../../assets/images/girl.jpg";
import shadow from "../../../../assets/images/shadow.jpg";
import poemTrain from "../../../../assets/images/poemTrain.jpg";

export const texts = [
  {
    id: 1,
    id_author: 1,
    author: "rose",
    title: "Los abrazos",
    genre: "writings",
    date: "11 may, 2020",
    picUrl: rose,
    category: "sentimientos",
    likes: 523,
    views: 1235,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "El amor es una enfermedad de las más jodidas y contagiosas. A los enfermos cualquiera nos reconoce. Hondas ojeras delatan que jamás dormimos, despabilados noche tras noche por los abrazos,",
    tags: ["amor", "alegría", "emotivo"],
  },
  {
    id: 2,
    id_author: 2,
    author: "juen_lo",
    title: "El mundo",
    genre: "writings",
    picUrl: people,
    date: "11 may, 2020",
    category: "sentimientos",
    likes: 710,
    views: 2356,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Un hombre del pueblo de Negua, en la costa de Colombia, pudo subir al alto cielo. A la vuelta, contó. Dijo que había contemplado, desde allá arriba, la vida humana. Y dijo que somos un mar de fueguitos",
    tags: ["amor", "pasión"],
  },
  {
    id: 3,
    id_author: 3,
    author: "justmi",
    title: "Ocaso",
    genre: "writings",
    picUrl:
      "https://c.wallhere.com/photos/12/ea/1534x863_px_artwork_Leonid_Afremov_painting_Sailboats_sea-514537.jpg!d",
    date: "11 may, 2020",
    category: "religión",
    likes: 1420,
    views: 3154,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "¿Cómo explican los sentimientos agradables? Afirmando que están determinados por la confianza de Dios, por la conciencia de haber hecho una buena acción (lo que llaman buena conciencia es un estado",
    tags: ["ética", "moral"],
  },
  {
    id: 4,
    id_author: 4,
    author: "dipme",
    title: "Charles",
    genre: "writings",
    picUrl: "https://huellas01.web.app/css/img/writing-4.jpg",
    date: "11 may, 2020",
    category: "política",
    likes: 1230,
    views: 3456,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Ahora, cuando cae la tarde tan despacio, me sorprendo arrimado al espejo nocturno, al silencio tan denso de miradas: parezco una lejana voz que apenas se dice, que despide amarilla al día que se fuga. Un día más se va.",
    tags: ["ética", "moral"],
  },
  {
    id: 5,
    id_author: 5,
    author: "redstone",
    title: "Vos",
    genre: "poems",
    picUrl: "https://huellas01.web.app/css/img/poem-1.jpg",
    date: "11 may, 2020",
    category: "verso-libre",
    likes: 3702,
    views: 6540,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Tengo la sensación de que algo me falta, no sé bien si seas vos o más alcohol, así que por si no volves, iré a conseguir cerveza, y si vienes, por favor trae cerveza. Lo sé, yo también odio ese vicio. Por eso te pido que",
    tags: ["amor", "miedo"],
  },
  {
    id: 6,
    id_author: 6,
    author: "famuel",
    title: "Fe",
    genre: "writings",
    picUrl: "https://huellas01.web.app/css/img/writing-6.jpg",
    date: "11 may, 2020",
    category: "religión",
    likes: [4, 1],
    views: 1202,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Sin fe, no tenemos esperanza, y sin esperanza no tenemos propiamente vida. No teniendo una idea del futuro, tampoco tenemos una idea de hoy, porque el hoy, para el hombre de acción, no es sino un prólogo del futuro",
    tags: ["cristianismo", "jesús"],
  },
  {
    id: 7,
    id_author: 7,
    author: "JenniferDel",
    title: "Charles",
    genre: "writings",
    picUrl: "https://huellas01.web.app/css/img/writing-4.jpg",
    date: "11 may, 2020",
    category: "sentimientos",
    likes: 5520,
    views: 9853,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Ahora, cuando cae la tarde tan despacio, me sorprendo arrimado al espejo nocturno, al silencio tan denso de miradas: parezco una lejana voz que apenas se dice, que despide amarilla al día que se fuga. Un día más se va.",
    tags: ["amor", "odio"],
  },
  {
    id: 8,
    id_author: 8,
    author: "TedReste",
    title: "Vos",
    genre: "poems",
    picUrl: "https://huellas01.web.app/css/img/poem-1.jpg",
    date: "11 may, 2020",
    category: "sentimientos",
    likes: 1230,
    views: 2356,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Tengo la sensación de que algo me falta, no sé bien si seas vos o más alcohol, así que por si no volves, iré a conseguir cerveza, y si vienes, por favor trae cerveza. Lo sé, yo también odio ese vicio. Por eso te pido que",
    tags: ["odio", "pasión"],
  },
  {
    id: 9,
    id_author: 9,
    author: "JoeGoldberg",
    title: "Fe",
    genre: "writings",
    picUrl: rose,
    date: "11 may, 2020",
    category: "sentimientos",
    likes: 722,
    views: 1463,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Sin fe, no tenemos esperanza, y sin esperanza no tenemos propiamente vida. No teniendo una idea del futuro, tampoco tenemos una idea de hoy, porque el hoy, para el hombre de acción, no es sino un prólogo del futuro",
    tags: ["felicidad", "emotivo"],
  },
  {
    id: 10,
    id_author: 10,
    author: "eSmI",
    title: "Charles",
    genre: "writings",
    picUrl: train,
    date: "11 may, 2020",
    category: "sentimientos",
    likes: 5405,
    views: 9856,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Tengo la sensación de que algo me falta, no sé bien si seas vos o más alcohol, así que por si no volves, iré a conseguir cerveza, y si vienes, por favor trae cerveza. Lo sé, yo también odio ese vicio.",
    tags: ["emotivo", "desamor"],
  },
  {
    id: 11,
    id_author: 11,
    author: "esTers",
    title: "Nadie sino tú",
    genre: "poems",
    picUrl: "https://huellas01.web.app/css/img/poem-1.jpg",
    date: "11 may, 2020",
    category: "verso-libre",
    likes: 3100,
    views: 5632,
    overview:
      "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. ",
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    tags: ["desamor", "odio", "pasión"],
  },
  {
    id: 12,
    id_author: 1,
    author: "rose",
    title: "Fe",
    genre: "writings",
    picUrl: "https://huellas01.web.app/css/img/writing-6.jpg",
    date: "11 may, 2020",
    category: "sentimientos",
    likes: 5350,
    views: 8789,
    overview:
      "Sin fe, no tenemos esperanza, y sin esperanza no tenemos propiamente vida. No teniendo una idea del futuro, tampoco tenemos una idea de hoy, porque el hoy, para el hombre de acción, no es sino un prólogo del futuro",
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    tags: ["amor", "melancolía"],
  },
  {
    id: 13,
    id_author: 7,
    author: "JenniferDel",
    title: "Charles",
    genre: "poems",
    picUrl: "https://huellas01.web.app/css/img/writing-4.jpg",
    date: "11 may, 2020",
    category: "verso-libre",
    likes: 5520,
    views: 9853,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Ahora, cuando cae la tarde tan despacio, me sorprendo arrimado al espejo nocturno, al silencio tan denso de miradas: parezco una lejana voz que apenas se dice, que despide amarilla al día que se fuga. Un día más se va.",
    tags: ["amor", "odio"],
  },
  {
    id: 14,
    id_author: 8,
    author: "TedReste",
    title: "Nadie puede salvarte sino tú mismo",
    genre: "poems",
    picUrl: "https://huellas01.web.app/css/img/poem-1.jpg",
    date: "11 may, 2020",
    category: "verso-libre",
    likes: 1230,
    views: 2356,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Tengo la sensación de que algo me falta, no sé bien si seas vos o más alcohol, así que por si no volves, iré a conseguir cerveza, y si vienes, por favor trae cerveza. Lo sé, yo también odio ese vicio. Por eso te pido que",
    tags: ["odio", "pasión"],
  },
  {
    id: 15,
    id_author: 9,
    author: "JoeGoldberg",
    title: "Fe",
    genre: "poems",
    picUrl: "https://huellas01.web.app/css/img/writing-6.jpg",
    date: "11 may, 2020",
    category: "verso-libre",
    likes: 722,
    views: 1463,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Sin fe, no tenemos esperanza, y sin esperanza no tenemos propiamente vida. No teniendo una idea del futuro, tampoco tenemos una idea de hoy, porque el hoy, para el hombre de acción, no es sino un prólogo del futuro",
    tags: ["felicidad", "emotivo"],
  },
  {
    id: 16,
    id_author: 10,
    author: "eSmI",
    title: "Charles",
    genre: "poems",
    picUrl: "https://huellas01.web.app/css/img/writing-4.jpg",
    date: "11 may, 2020",
    category: "verso-libre",
    likes: 5405,
    views: 9856,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Ahora, cuando cae la tarde tan despacio, me sorprendo arrimado al espejo nocturno, al silencio tan denso de miradas: parezco una lejana voz que apenas se dice, que despide amarilla al día que se fuga. Un día más se va.",
    tags: ["emotivo", "desamor"],
  },
  {
    id: 17,
    id_author: 11,
    author: "esTers",
    title: "Vos",
    genre: "poems",
    picUrl: "https://huellas01.web.app/css/img/poem-1.jpg",
    date: "11 may, 2020",
    category: "verso-libre",
    likes: 3100,
    views: 5632,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Tengo la sensación de que algo me falta, no sé bien si seas vos o más alcohol, así que por si no volves, iré a conseguir cerveza, y si vienes, por favor trae cerveza. Lo sé, yo también odio ese vicio. Por eso te pido que",
    tags: ["desamor", "odio", "pasión"],
  },
  {
    id: 18,
    id_author: 1,
    author: "rose",
    title: "Fe",
    genre: "poems",
    picUrl: "https://huellas01.web.app/css/img/writing-6.jpg",
    date: "11 may, 2020",
    category: "verso-libre",
    likes: 5350,
    views: 8789,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Sin fe, no tenemos esperanza, y sin esperanza no tenemos propiamente vida. No teniendo una idea del futuro, tampoco tenemos una idea de hoy, porque el hoy, para el hombre de acción, no es sino un prólogo del futuro",
    tags: ["amor", "melancolía"],
  },
  {
    id: 19,
    id_author: 4,
    author: "dipme",
    title: "Charles",
    genre: "writings",
    picUrl: "https://huellas01.web.app/css/img/writing-4.jpg",
    date: "11 may, 2020",
    category: "política",
    likes: 1230,
    views: 3456,
    text: "Nadie puede salvarte sino tú mismo. Te verás una y otra vez en situaciones casi imposibles. intentarán una y otra vez por medio de subterfugios, engaños o por la fuerza que renuncies, te des por vencido y/o mueras lentamente por dentro. Nadie puede salvarte sino tú mismoy será muy fácil desfallecer, pero muy fácil, pero no desfallezcas, no, no. limítate a mirarlos. escucharlos. <br /> <br />¿quieres ser así? ¿un ser sin cara, sin mente, sin corazón? ¿quieres experimentar la muerte antes de la muerte? nadie puede salvarte sino tú mismo y mereces salvarte. no es una guerra fácil de ganar pero si algo merece la pena ganar, es esto. piénsalo. piensa en salvarte a ti mismo. tu parte espiritual. la parte de tus entrañas. tu parte mágica y ebria. sálvala. <br /><br />no te unas a los muertos de espíritu. mantente con buen talante y garbo y al cabo, si fuera necesario, apuesta tu vida en plena refriega, al carajo las probabilidades, al carajo el precio. nadie puede salvarte sino tú mismo. ¡Hazlo! ¡sálvate! entonces sabrás exactamente de qué hablo.",
    overview:
      "Ahora, cuando cae la tarde tan despacio, me sorprendo arrimado al espejo nocturno, al silencio tan denso de miradas: parezco una lejana voz que apenas se dice, que despide amarilla al día que se fuga. Un día más se va.",
    tags: ["ética", "moral"],
  },
  {
    id: 20,
    id_author: 4,
    author: "dipme",
    title: "Charles",
    genre: "writings",
    picUrl: "https://huellas01.web.app/css/img/writing-4.jpg",
    date: "11 may, 2020",
    category: "política",
    likes: 1230,
    views: 3456,
    overview:
      "Ahora, cuando cae la tarde tan despacio, me sorprendo arrimado al espejo nocturno, al silencio tan denso de miradas: parezco una lejana voz que apenas se dice, que despide amarilla al día que se fuga. Un día más se va.",
    tags: ["ética", "moral"],
  },
  {
    id: 21,
    id_author: 4,
    author: "dipme",
    title: "Charles",
    genre: "writings",
    picUrl: "https://huellas01.web.app/css/img/writing-4.jpg",
    date: "11 may, 2020",
    category: "política",
    likes: 1230,
    views: 3456,
    overview:
      "Ahora, cuando cae la tarde tan despacio, me sorprendo arrimado al espejo nocturno, al silencio tan denso de miradas: parezco una lejana voz que apenas se dice, que despide amarilla al día que se fuga. Un día más se va.",
    tags: ["ética", "moral"],
  },
  {
    id: 22,
    id_author: 4,
    author: "dipme",
    title: "Charles",
    genre: "writings",
    picUrl: "https://huellas01.web.app/css/img/writing-4.jpg",
    date: "11 may, 2020",
    category: "política",
    likes: 1230,
    views: 3456,
    overview:
      "Ahora, cuando cae la tarde tan despacio, me sorprendo arrimado al espejo nocturno, al silencio tan denso de miradas: parezco una lejana voz que apenas se dice, que despide amarilla al día que se fuga. Un día más se va.",
    tags: ["ética", "moral"],
  },
  {
    id: 23,
    id_author: 5,
    author: "redstone",
    title: "Vos",
    genre: "poems",
    picUrl: "https://huellas01.web.app/css/img/poem-1.jpg",
    date: "11 may, 2020",
    category: "verso-libre",
    likes: 3702,
    views: 6540,
    overview:
      "Tengo la sensación de que algo me falta, no sé bien si seas vos o más alcohol, así que por si no volves, iré a conseguir cerveza, y si vienes, por favor trae cerveza. Lo sé, yo también odio ese vicio. Por eso te pido que",
    tags: ["amor", "miedo"],
  },
  {
    id: 24,
    id_author: 6,
    author: "famuel",
    title: "Fe",
    genre: "writings",
    picUrl: "https://huellas01.web.app/css/img/writing-6.jpg",
    date: "11 may, 2020",
    category: "religión",
    likes: 621,
    views: 1202,
    overview:
      "Sin fe, no tenemos esperanza, y sin esperanza no tenemos propiamente vida. No teniendo una idea del futuro, tampoco tenemos una idea de hoy, porque el hoy, para el hombre de acción, no es sino un prólogo del futuro",
    tags: ["cristianismo", "jesús"],
  },
  {
    id: 25,
    id_author: 5,
    author: "redstone",
    title: "Vos",
    genre: "poems",
    picUrl: "https://huellas01.web.app/css/img/poem-1.jpg",
    date: "11 may, 2020",
    category: "verso-libre",
    likes: 3702,
    views: 6540,
    overview:
      "Tengo la sensación de que algo me falta, no sé bien si seas vos o más alcohol, así que por si no volves, iré a conseguir cerveza, y si vienes, por favor trae cerveza. Lo sé, yo también odio ese vicio. Por eso te pido que",
    tags: ["amor", "miedo"],
  },
  {
    id: 26,
    id_author: 6,
    author: "famuel",
    title: "Fe",
    genre: "writings",
    picUrl: "https://huellas01.web.app/css/img/writing-6.jpg",
    date: "11 may, 2020",
    category: "religión",
    likes: 621,
    views: 1202,
    overview:
      "Sin fe, no tenemos esperanza, y sin esperanza no tenemos propiamente vida. No teniendo una idea del futuro, tampoco tenemos una idea de hoy, porque el hoy, para el hombre de acción, no es sino un prólogo del futuro",
    tags: ["cristianismo", "jesús"],
  },
  {
    id: 27,
    id_author: 5,
    author: "redstone",
    title: "Vos",
    genre: "poems",
    picUrl: "https://huellas01.web.app/css/img/poem-1.jpg",
    date: "11 may, 2020",
    category: "verso-libre",
    likes: 3702,
    views: 6540,
    overview:
      "Tengo la sensación de que algo me falta, no sé bien si seas vos o más alcohol, así que por si no volves, iré a conseguir cerveza, y si vienes, por favor trae cerveza. Lo sé, yo también odio ese vicio. Por eso te pido que",
    tags: ["amor", "miedo"],
  },
  {
    id: 28,
    id_author: 6,
    author: "famuel",
    title: "Fe",
    genre: "writings",
    picUrl: "https://huellas01.web.app/css/img/writing-6.jpg",
    date: "11 may, 2020",
    category: "religión",
    likes: 621,
    views: 1202,
    overview:
      "Sin fe, no tenemos esperanza, y sin esperanza no tenemos propiamente vida. No teniendo una idea del futuro, tampoco tenemos una idea de hoy, porque el hoy, para el hombre de acción, no es sino un prólogo del futuro",
    tags: ["cristianismo", "jesús"],
  },
];
